@url = http://localhost:3000/api/v1

@currentToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDllNDhiMDdhZGRlODA0N2FjNWFmODkiLCJpYXQiOjE2MjE0OTgyMjl9.kNHJTcxBxcpJamEcQTqqf_H83TD32X4ldpZX5vK4VQQ

POST {{url}}/trip/createTrip
Authorization: Bearer {{currentToken}}
content-type: application/json

{
    "name": "Bangkok202109",
    "startDate": "2021-05-20T00:00:00.000Z",
    "endDate": "2021-03-20T00:00:00.000Z",
}

###
