@url = http://localhost:3000/api/v1

@currentToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDllMWQwNzhhNmM5NTA2ZWI0MTAwZjUiLCJpYXQiOjE2MjA5NzQ4NTV9.urZ8AYw6BBBszygvC1j5jqnAnevEBQZlzHVxT4R0fO4

POST {{url}}/user/signUp
content-type: application/json

{
    "name": "Dennis",
    "email": "he@abc.com",
    "password": "123456"
}

###
POST {{url}}/user/login
content-type: application/json

{
    "email": "he@abc.com",
    "password": "123456"
}

###
GET {{url}}/user/profile
Authorization: Bearer {{currentToken}}


