@url = http://localhost:3000/api/v1

@currentToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDllNDhiMDdhZGRlODA0N2FjNWFmODkiLCJpYXQiOjE2MjE0OTgyMjl9.kNHJTcxBxcpJamEcQTqqf_H83TD32X4ldpZX5vK4VQQ

POST {{url}}/user/signUp
content-type: application/json

{
    "name": "Dennis",
    "email": "he@abc.com",
    "password": "123456"
}

###
POST {{url}}/user/login
content-type: application/json

{
    "email": "he@abc.com",
    "password": "123456"
}

###
GET {{url}}/user/profile
Authorization: Bearer {{currentToken}}

###
PATCH {{url}}/user/profile
Authorization: Bearer {{currentToken}}
content-type: application/json

{
    "name": "Smith"
}
 

###
POST {{url}}/user/logout
Authorization: Bearer {{currentToken}}

###

