@url = http://localhost:3000/api/v1

@currentToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDllNDhiMDdhZGRlODA0N2FjNWFmODkiLCJpYXQiOjE2MjEzMzU4Njl9.xB9BgIouuCZkrRq3OsCsgydkiFy-GVBt--mX4RCxmew

POST {{url}}/user/signUp
content-type: application/json

{
    "name": "Dennis",
    "email": "he@abc.com",
    "password": "123456"
}

###
POST {{url}}/user/login
content-type: application/json

{
    "email": "he@abc.com",
    "password": "123456"
}

###
GET {{url}}/user/profile
Authorization: Bearer {{currentToken}}


###
POST {{url}}/user/logout
Authorization: Bearer {{currentToken}}


